title: EngrSMukhtar
author: Sani Mukhtar
email: Hi@EngrSMukhtar.com
description: > This is the blog of EngrSMukhtar # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

# social links
[twitter_username](https://twitter.com/EngrSMukhtar): https://twitter.com/EngrSMukhtar
[github_username](https://github.com/EngrSMukhtar):  https://github.com/EngrSMukhtar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
